name: Deploy
permissions:
  contents: read
  actions: read
on:
  workflow_run:
    workflows: ["Build and Push"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      - name: Copy deploy script and run on server
        run: 
          scp -o StrictHostKeyChecking=no infra/deploy_on_server.sh ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }}:/tmp/deploy_on_server.sh
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} 'bash /tmp/deploy_on_server.sh'
